export default {
    OPEN_FILE: "OPEN_FILE",
    SAVE: "SAVE",
    CLOSE: "CLOSE",
    ALWAYS_SHOW_MENUBAR: "ALWAYS_SHOW_MENUBAR",
    ALWAYS_SHOW_LEFT_SIDEBAR: "ALWAYS_SHOW_LEFT_SIDEBAR",
    ALWAYS_SHOW_RIGHT_SIDEBAR: "ALWAYS_SHOW_RIGHT_SIDEBAR"
};